service: baltika-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DB_HOST: baltikadb.ctioae0mycpp.us-east-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_USER: admin
    DB_PASSWORD: Baltika2025*
    DB_NAME: baltikadb
    COGNITO_USER_POOL_ID: us-east-1_y3DKBQYxn
  httpApi:
    cors:
      allowedOrigins:
        - 'http://localhost:4200'
        - 'https://baltikeishon.com'
        - 'https://www.baltikeishon.com'
        - 'https://myclub.baltikeishon.com'
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowedHeaders:
        - '*'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:ListUsers
            - cognito-idp:AdminDisableUser
            - cognito-idp:AdminEnableUser
            - cognito-idp:AdminUpdateUserAttributes
          Resource: 
            - arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/${self:provider.environment.COGNITO_USER_POOL_ID}
functions:
  updateUserStatus:
    handler: dist/functions/updateUserStatus.handler
    events:
      - httpApi:
          method: put
          path: /users/status
    timeout: 30
  updateUserTeam:
    handler: dist/functions/updateUserTeam.handler
    events:
      - httpApi:
          method: put
          path: /users/team
    timeout: 30
  getUsers:
    handler: dist/functions/getUsers.handler
    events:
      - httpApi:
          method: get
          path: /users
    timeout: 30
  getUser:
    handler: dist/functions/getUser.handler
    events:
      - httpApi:
          method: get
          path: /users/{username}
    timeout: 30
  getMatches:
    handler: dist/functions/getMatches.handler
    events:
      - httpApi:
          method: get
          path: /match
  getMatchDetail:
    handler: dist/functions/getMatchDetail.handler
    events:
      - httpApi:
          method: get
          path: /match/detail
  generateMatches:
    handler: dist/functions/generateMatches.handler
    events:
      - httpApi:
          method: post
          path: /generate-matches
    timeout: 60
  createTournament:
    handler: dist/functions/createTournament.handler
    events:
      - httpApi:
          method: post
          path: /tournament
  createSeason:
    handler: dist/functions/createSeason.handler
    events:
      - httpApi:
          method: post
          path: /seasons
  createTeam:
    handler: dist/functions/createTeam.handler
    events:
      - httpApi:
          method: post
          path: /teams
  updateTeam:
    handler: dist/functions/updateTeam.handler
    events:
      - httpApi:
          method: put
          path: /teams
    timeout: 30
  updateMatch:
    handler: dist/functions/updateMatch.handler
    events:
      - httpApi:
          method: put
          path: /match
    timeout: 30
  deletePlayerStatistics: 
    handler: dist/functions/deletePlayerStatistics.handler
    events:
      - httpApi:
          method: delete
          path: /match/statistics
    timeout: 30
  getPositions:
    handler: dist/functions/getPositions.handler
    events:
      - httpApi:
          method: get
          path: /positions
    timeout: 30
  getTeams:
    handler: dist/functions/getTeams.handler
    events:
      - httpApi:
          method: get
          path: /teams
  getPlayer:
    handler: dist/functions/getPlayer.handler
    events:
      - httpApi:
          method: get
          path: /players/{id}
    timeout: 30
  getPlayers:
    handler: dist/functions/getPlayers.handler
    events:
      - httpApi:
          method: get
          path: /players
    timeout: 600
  getSquad:
    handler: dist/functions/getSquad.handler
    events:
      - httpApi:
          method: get
          path: /squad
    timeout: 30
  updateRegisterPlayer:
    handler: dist/functions/updateRegisterPlayer.handler
    events:
      - httpApi:
          method: put
          path: /squad
    timeout: 30
  getOffers:
    handler: dist/functions/getOffers.handler
    events:
      - httpApi:
          method: get
          path: /offer
    timeout: 30
  createOffer:
    handler: dist/functions/createOffer.handler
    events:
      - httpApi:
          method: post
          path: /offer
    timeout: 30
  updateOffer:
    handler: dist/functions/updateOffer.handler
    events:
      - httpApi:
          method: put
          path: /offer
    timeout: 30
  updateStatusOffer:
    handler: dist/functions/updateStatusOffer.handler
    events:
      - httpApi:
          method: put
          path: /offer/status
    timeout: 30
  getBubget:
    handler: dist/functions/getBudget/index.handler
    events:
      - httpApi:
          method: get
          path: /budget
    timeout: 30
  getScorers:
    handler: dist/functions/getScorers.handler
    events:
      - httpApi:
          method: get
          path: /scorers
    timeout: 30
  getSeasons:
    handler: dist/functions/getSeasons.handler
    events:
      - httpApi:
          method: get
          path: /seasons
    timeout: 30
  getTournaments:
    handler: dist/functions/getTournaments.handler
    events:
      - httpApi:
          method: get
          path: /tournaments
    timeout: 30
  deleteSeason:
    handler: dist/functions/deleteSeason.handler
    events:
      - httpApi:
          method: delete
          path: /seasons/{id}
    timeout: 30
  getSeasonById:
    handler: dist/functions/getSeasonById.handler
    events:
      - httpApi:
          method: get
          path: /seasons/{id}
    timeout: 30
  updateSeason:
    handler: dist/functions/updateSeason.handler
    events:
      - httpApi:
          method: put
          path: /seasons/{id}
    timeout: 30
  addTeamToSeason:
    handler: dist/functions/addTeamToSeason.handler
    events:
      - httpApi:
          method: post
          path: /seasons/{seasonId}/teams
    timeout: 30
  getSeasonTeams:
    handler: dist/functions/getSeasonTeams.handler
    events:
      - httpApi:
          method: get
          path: /seasons/{seasonId}/teams
    timeout: 30
  updateSeasonTeams:
    handler: dist/functions/updateSeasonTeams.handler
    events:
      - httpApi:
          method: put
          path: /seasons/{seasonId}/teams
    timeout: 30
  getFixtureStats:
    handler: dist/functions/getFixtureStats.handler
    events:
      - httpApi:
          method: get
          path: /seasons/{seasonId}/fixture-stats
    timeout: 30
  recreateFixture:
    handler: dist/functions/recreateFixture.handler
    events:
      - httpApi:
          method: post
          path: /recreate-fixture
    timeout: 60
  addAuctions:
    handler: dist/functions/auctions/addAuction.handler
    events:
      - httpApi:
          method: post
          path: /auctions
    timeout: 30
  getAuctions:
    handler: dist/functions/auctions/getAuctions.handler
    events:
      - httpApi:
          method: get
          path: /auctions
  withdrawAuction:
    handler: dist/functions/auctions/withdrawAuction.handler
    events:
      - httpApi:
          method: delete
          path: /auctions
    timeout: 30
  activateSeason:
    handler: dist/functions/activateSeason.handler
    events:
      - httpApi:
          method: put
          path: /seasons/{id}/activate
    timeout: 30
  updateSeasonDates:
    handler: dist/functions/updateSeasonDates.handler
    events:
      - httpApi:
          method: put
          path: /seasons/{id}/dates
    timeout: 30
plugins:
  - serverless-offline